<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php


?>
<?php if($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price ):?>
<?php $range =  $this->getPriceRange($filter);?>
<?php $url = $this->getFilterUrl($filter);?>
<?php
    $symbol = $this->getStore()->getCurrentCurrency()->getCurrencySymbol();
?>
<style type="text/css">
.filter-options-content a{-webkit-transition:none !important;}
</style>
<script>
var price_url = "<?=$url;?>";
require([
    'jquery',
    "jquery/ui",
    'domReady!'
], function($){
    function setParam(data, name, value){
        var tmp = '';
        var flag = false;
        var result = '';
        if(data){
            tmp = data.split('&');
        }
        if(tmp.length > 0){
            for(var i = 0; i < tmp.length; i++){
                var tmp2 = tmp[i].split('=');
                if(tmp2.length > 1 && tmp2[0] == name)
                {
                    tmp2[1] = value;
                    flag = true;
                }
                if(tmp2.length > 1){
                    result += ('&' + tmp2[0] + '=' + tmp2[1]);
                }
            }
        }
        if(!flag){
            result += ('&' + name + '=' + value);
        }
        return result;
    }
    
    function getHref(from,to){
        uriRequest = setParam(uriRequest, 'price', from+'-'+to);
        var href = window.location.href + "?" + uriRequest.replace(catparam,'');
        console.log(href);
        $('#price-fake').attr('href',href);
    }
    $("div#price-slider").slider({
		min: <?php echo $range['min']?>,
		max: <?php echo $range['max']?>,
        animation: 'fast',
		values: [ <?php echo $range['min']?>, <?php echo $range['max']?> ],
		slide: function( event, ui ) {
			$("#price-from").val(ui.values[ 0 ]);
			$("#price-to").val(ui.values[ 1 ]);
		}
	});
	$("#price-from").val($( "#price-slider" ).slider( "values", 0 ));
	$("#price-to").val($( "#price-slider" ).slider( "values", 1 ));
	$("#apply-price").click(function(){
	    getHref($("#price-from").val(), $("#price-to").val());
	    $('#price-fake').click();
	});
});
</script>
<?php 
?>      
<div class=“price-control-wrapper” style="margin-bottom:45px;">
	<div id="price-slider"></div>
	<div class=“price-form” style="float:left"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($range['min']) ?></div>
	<div class=“price-to” style="float:right"><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($range['max']) ?></div>
</div>

<div class="price-control">
    <label><?php echo $symbol ?></label><input type="text" id="price-from" style="width:40px"/>
    <span> ~ </span>
    <label><?php echo $symbol ?></label><input type="text" id="price-to" style="width:40px"/>
    <button class="button" id="apply-price" style="float:right"><span><span><?php echo __("Go") ?></span></span></button>
</div>

<a href="#" id="price-fake" style="display:none"></a>
<?php else:?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="my item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?php /* @escapeNotVerified */ echo __('item')?><?php else:?> <?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @escapeNotVerified */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?php /* @escapeNotVerified */ echo $filterItem->getCount()?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?php /* @escapeNotVerified */ echo __('item')?><?php else:?><?php /* @escapeNotVerified */ echo __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php endif;?>
